const SHOPPING_CART_ACTIONS = {
    ACTION_SHOPPING_CART_REQUEST: 'ACTION_SHOPPING_CART_REQUEST',
    ACTION_SHOPPING_CART_ADD: 'ACTION_SHOPPING_CART_ADD',
    ACTION_SHOPPING_CART_ADD_SUCCESS: 'ACTION_SHOPPING_CART_ADD_SUCCESS',
    ACTION_SHOPPING_CART_GET: 'ACTION_SHOPPING_CART_GET',
    ACTION_SHOPPING_CART_GET_SUCCESS: 'ACTION_SHOPPING_CART_GET_SUCCESS',
    ACTION_SHOPPING_CART_DELETE_ITEM: 'ACTION_SHOPPING_CART_DELETE_ITEM',
    ACTION_SHOPPING_CART_DELETE_ITEM_SUCCESS: 'ACTION_SHOPPING_CART_DELETE_ITEM_SUCCESS',
    ACTION_SHOPPING_CART_ERROR: 'ACTION_SHOPPING_CART_ERROR',
    ACTION_CLEAR_SHOPPING_CART_MESSAGE_AND_ERROR: 'ACTION_CLEAR_SHOPPING_CART_MESSAGE_AND_ERROR',
    ACTION_CLEAR_SHOPPING_CART: 'ACTION_CLEAR_SHOPPING_CART'
};

export default SHOPPING_CART_ACTIONS;