const SMARTPHONES_ACTIONS = {
    ACTION_SMARTPHONES_REQUEST: 'ACTION_SMARTPHONES_REQUEST',
    ACTION_GET_SMARTPHONES: 'ACTION_GET_SMARTPHONES',
    ACTION_GET_SMARTPHONES_SUCCESS: 'ACTION_GET_SMARTPHONES_SUCCESS',
    ACTION_GET_SMARTPHONE: 'ACTION_GET_SMARTPHONE',
    ACTION_GET_SMARTPHONE_SUCCESS: 'ACTION_GET_SMARTPHONE_SUCCESS',
    ACTION_CREATE_SMARTPHONE: 'ACTION_CREATE_SMARTPHONE',
    ACTION_CREATE_SMARTPHONE_SUCCESS: 'ACTION_CREATE_SMARTPHONE_SUCCESS',
    ACTION_CLEAR_SMARTPHONES: 'ACTION_CLEAR_SMARTPHONES',
    ACTION_CLEAR_SMARTPHONE: 'ACTION_CLEAR_SMARTPHONE'
};

export default SMARTPHONES_ACTIONS;