const AUTH_ACTIONS = {
    ACTION_AUTH_REQUEST: 'ACTION_AUTH_REQUEST',
    ACTION_LOGIN: 'ACTION_LOGIN',
    ACTION_LOGIN_SUCCESS: 'ACTION_LOGIN_SUCCESS',
    ACTION_SIGNUP: 'ACTION_SIGNUP',
    ACTION_SIGNUP_SUCCESS: 'ACTION_SIGNUP_SUCCESS',
    ACTION_AUTH_SUCCESS: 'ACTION_AUTH_SUCCESS',
    ACTION_AUTH_ERROR: 'ACTION_AUTH_ERROR',
    ACTION_AUTH_CLEAR_ERROR: 'ACTION_AUTH_CLEAR_ERROR',
    ACTION_LOGOUT: 'ACTION_LOGOUT'
};

export default AUTH_ACTIONS;