const ORDERS_ACTIONS = {
    ACTION_ORDERS_REQUEST: 'ACTION_ORDERS_REQUEST',
    ACTION_CONFIRM_ORDER: 'ACTION_CONFIRM_ORDER',
    ACTION_GET_ORDERS: 'ACTION_GET_ORDERS',
    ACTION_GET_ORDERS_SUCCESS: 'ACTION_GET_ORDERS_SUCCESS',
    ACTION_CHANGE_ORDER_STATUS: 'ACTION_CHANGE_ORDER_STATUS',
    ACTION_CHANGE_ORDER_STATUS_SUCCESS: 'ACTION_CHANGE_ORDER_STATUS_SUCCESS'
};

export default ORDERS_ACTIONS;