const USER_ACTIONS = {
    ACTION_USER_REQUEST: 'ACTION_USER_REQUEST',
    ACTION_GET_USER: 'ACTION_GET_USER',
    ACTION_GET_USER_SUCCESS: 'ACTION_GET_USER_SUCCESS',
    ACTION_USER_ERROR: 'ACTION_GET_USER'
};

export default USER_ACTIONS;